---
- name: Configure db
  hosts: db 
  gather_facts: no
  become: True
  tasks:

  - name: Create docker-compose.yml for "{{ inventory_hostname }}"
    ansible.builtin.template:
      src: ../../templates/db/docker-compose.yml.j2
      dest: /tmp/docker-compose.yml
      owner: root
      group: root
      mode: '177'
        
  - name: Wait for /var/lib/dpkg/lock-frontend to be released 
    ansible.builtin.shell: while lsof /var/lib/dpkg/lock-frontend ; do sleep 10; done;

  - name: Install Docker
    ansible.builtin.apt: 
      name: docker-compose 
      update_cache: yes
    register: apt_res
    retries: 5
    until: apt_res is success

  # use files parameter to use multiple docker-compose.yml files
  - name: Deploy Docker Compose stack
    community.docker.docker_compose:
      project_src: /tmp/
      files:
      - docker-compose.yml
#      - docker-compose.prod.yml
