---
- name: Configure db
  hosts: db 
  gather_facts: no
  become: True
  tasks:
  - name: Wait for the reboot and reconnect "{{ inventory_hostname }}"
    ignore_unreachable: no
    ansible.builtin.wait_for:
      port: 22
      host: "{{ inventory_hostname }}"
      search_regex: OpenSSH
      delay: "{{ wait_vm_delay }}" 
      timeout: "{{ wait_vm_timeout }}"
    connection: local

  - name: Create docker-compose.yml for "{{ ansible_play_batch }}"
    ansible.builtin.template:
      src: ../../templates/db/docker-compose.yml.j2
      dest: /tmp/docker-compose.yml
#      owner: root
#      group: root
#      mode: '1777'

  - name: Deploy Docker Compose stack
    community.docker.docker_compose:
      project_src: /tmp/
      files:
      - docker-compose.yml
#      - docker-compose.prod.yml
#    async: 60
#    poll: 60
