---
- name: Configure firewall
  hosts: gw
  gather_facts: no
  become: True
  tasks:

  - name: Wait for the reboot and reconnect "{{ inventory_hostname }}"
    ignore_unreachable: no
    ansible.builtin.wait_for:
      port: 22
      host: "{{ inventory_hostname }}"
      search_regex: OpenSSH
      delay: "{{ wait_vm_delay }}" 
      timeout: "{{ wait_vm_timeout }}"
    connection: local

  - name: Wait for /var/lib/dpkg/lock-frontend to be released on "{{ inventory_hostname }}"
    ansible.builtin.shell: while lsof /var/lib/dpkg/lock-frontend ; do sleep 10; done;

  - name: Enabling ipv4_forwarding on "{{ inventory_hostname }}"
    ansible.posix.sysctl:
      name: net.ipv4.ip_forward
      value: '1'
      sysctl_set: true
      state: present
      reload: true
      
  - name: Install iptables-persistent on "{{ inventory_hostname }}"
    ansible.builtin.apt: 
      name: iptables-persistent 
      update_cache: yes 
    register: apt_res
    retries: 5
    until: apt_res is success  

  - name: Create iptables fw script on "{{ inventory_hostname }}"
    ansible.builtin.template:
      src: ../../templates/gw/iptables.sh.j2
      dest: "/tmp/iptables.sh"
#      owner: root
#      group: root
#      mode: '0755'
      
  - name: Execute fw script on "{{ inventory_hostname }}"
    ansible.builtin.command: sh /tmp/iptables.sh      
      
