---
- name: Install Wordpress
  hosts: wordpress
#  gather_facts: no 
  become: True
  vars:
    src: "../../templates/wordpress/docker-compose.yml.j2"
    dst: "/tmp/docker-compose.yml"
  tasks:
  - name: Create docker-compose.yml for "{{ ansible_play_batch }}"
    ansible.builtin.template:
      src: "{{ src }}"
      dest: "{{ dst }}"
#      owner: root
#      group: root
#      mode: '1777'
    notify:
    - Deploy docker-compose.yml 


  handlers:
  - name: Deploy docker-compose.yml 
    community.docker.docker_compose:
      project_src: /tmp/
      files:
      - docker-compose.yml
#      - docker-compose.prod.yml
#    async: 60
#    poll: 60
