gw:
  hosts:
    10.0.10.1:

nginx:
  hosts:
    10.0.10.10:

wordpress:
  hosts:
    10.0.10.11:
    10.0.10.12:

db:
  hosts:
    10.0.10.20:

proxmox:
  hosts:
    172.18.18.68:
  vars:  
    ansible_connection: ssh
    ansible_user: root

docker_group:
  children:
    db:
    wordpress:

vm_create_group:
  children:
    gw:
    nginx:
    docker_group:



