---
- name: Create VM's
  hosts: vm_create_group 
  gather_facts: no
  become: True
              
  roles:
#  - { role: create_vm, when: ansible_somevar == 'some_condition' }
  - { role: create_vm }

- name: Configure gw
  hosts: gw
  gather_facts: no
  become: True
  roles:
  - { role: configure_gw }

- name: Install docker
  hosts: docker_group 
  gather_facts: no
  become: True
  roles:
  - { role: install_docker }

- name: Install mysql
  hosts: db
  gather_facts: no
  become: True
  roles:
  - { role: install_mysql }

- name: Install wordpress
  hosts: wordpress
  gather_facts: no
  become: True
  roles:
  - { role: install_wordpress }

- name: Install nginx
  hosts: nginx
  gather_facts: no
  become: True
  roles:
  - { role: install_nginx }
