---
- name: Create VMs
  ansible.builtin.import_playbook: tasks/create_vm.yml

- name: Configure VM GW
  ansible.builtin.import_playbook: tasks/config_vm/gw.yml

- name: Configure VM Nginx
  ansible.builtin.import_playbook: tasks/config_vm/nginx.yml

- name: Configure VM db
  ansible.builtin.import_playbook: tasks/config_vm/db.yml

- name: Configure VM Docker
  ansible.builtin.import_playbook: tasks/config_vm/docker.yml

