---
- name: Start VMs 
  hosts: vm_create_group
  gather_facts: no
  become: True
  tasks:
  - name: Get VM status
    community.general.proxmox_kvm:
      api_user: "{{ api_user }}"
      api_token_id: "{{ api_token_id }}"
      api_token_secret: "{{ api_token_secret }}"
      api_host: "{{ api_host }}"
      node: "{{ node }}"
      vmid: "{{ vmid }}"
      state: current 
    register: vm
    delegate_to: "{{ proxmox }}"

  - name: Print var
    debug:
      msg: "{{ vm }}"

  - name: Spinning up VM's...
    community.general.proxmox_kvm:
      api_user: "{{ api_user }}"
      api_token_id: "{{ api_token_id }}"
      api_token_secret: "{{ api_token_secret }}"
      api_host: "{{ api_host }}"
      node: "{{ node }}"
      vmid: "{{ vmid }}"
      state: started
    register: tmp_state
    retries: 5
    until: tmp_state is changed
    when: vm.status == "stopped"
    delegate_to: "{{ proxmox }}"

  - name: Get VM status
    community.general.proxmox_kvm:
      api_user: "{{ api_user }}"
      api_token_id: "{{ api_token_id }}"
      api_token_secret: "{{ api_token_secret }}"
      api_host: "{{ api_host }}"
      node: "{{ node }}"
      vmid: "{{ vmid }}"
      state: current
    register: vm
    delegate_to: "{{ proxmox }}"

  - name: Print var
    debug:
      msg: "{{ vm.status }}"

  - name: Wait for the reboot and reconnect
    ignore_unreachable: no
    ansible.builtin.wait_for:
      port: 22
      host: "{{ inventory_hostname }}"
      search_regex: OpenSSH
      delay: "{{ wait_vm_delay }}" 
      timeout: "{{ wait_vm_timeout }}"
    delegate_to: localhost

  - name: Ping VM's
    ansible.builtin.ping:
    ignore_errors: true 
