---
- name: Configure "{{ target_group }}"
  hosts: "{{ target_group }}"
#  ignore_unreachable: yes
  gather_facts: no
  become: True
  tasks:
#  - name: clone cloud-init from template
#    community.general.proxmox_kvm:
#      api_user: "{{ api_user }}"
#      api_token_id: "{{ api_token_id }}"
#      api_token_secret: "{{ api_token_secret }}"
#      api_host: "{{ api_host }}"
#      node: "{{ node }}"
#      clone: "{{ template }}"
#      newid: "{{ item.value.vmid }}"
#      full: "{{ full }}"
#      name: "{{ item.key }}"
#      bootdisk: "virtio0"
#      format: 'unspecified'
#      timeout: 600
#    delegate_to: "{{ proxmox }}"
    
  - name: Cconnect NIC net0 to bridge id 1
    community.general.proxmox_nic:
      api_user: "{{ api_user }}"
      api_token_id: "{{ api_token_id }}"
      api_token_secret: "{{ api_token_secret }}"
      api_host: "{{ api_host }}"
      vmid: "{{ item.value.vmid }}"
      interface: net0
      bridge: vmbr1
      firewall: false
    delegate_to: "{{ proxmox }}"
        
  - name: Update Network Settings
    community.general.proxmox_kvm:
      api_user: "{{ api_user }}"
      api_token_id: "{{ api_token_id }}"
      api_token_secret: "{{ api_token_secret }}"
      api_host: "{{ api_host }}"
      node: "{{ node }}"
      vmid: "{{ item.value.vmid }}"
      cores: '{{ cores | default(defaults.cores) }}'
      memory: '{{ memory_size | default(defaults.memory_size) }}'
      balloon: '{{ balloon | default(defaults.balloon) }}'
      net: '{{ net | default(defaults.net) }}'
      ipconfig: '{{ item.value.ipconfig | default(defaults.ipconfig) }}'
      sshkeys: '{{ sshkeys | default(defaults.sshkeys) }}'
      onboot: true
      update: true
    delegate_to: "{{ proxmox }}"
        
  - name: Start VM
    community.general.proxmox_kvm:
      api_user: "{{ api_user }}"
      api_token_id: "{{ api_token_id }}"
      api_token_secret: "{{ api_token_secret }}"
      api_host: "{{ api_host }}"
      node: "{{ node }}"
      vmid: "{{ item.value.vmid }}"
      state: started
    delegate_to: "{{ proxmox }}"

  - name: Wait for the reboot and reconnect
    ignore_unreachable: no
    ansible.builtin.wait_for:
      port: 22
      host: "{{ inventory_hostname }}"
      search_regex: OpenSSH
      delay: "{{ wait_vm_delay }}" 
      timeout: "{{ wait_vm_timeout }}"
    connection: local
 
