---
- name: Create VM Nginx
  ansible.builtin.import_playbook: ./create.yml
  vars:
    target_group: "nginx"

- name: Configure nginx lb
  hosts: nginx
  become: True
  tasks:
  - name: Wait for reboot '{{ inventory_hostname }}'
    ansible.builtin.wait_for:
      port: 22
      host: '{{ inventory_hostname }}'
      search_regex: OpenSSH
      delay: "{{ wait_vm_delay }}" 
      timeout: "{{ wait_vm_timeout }}"
    connection: local

  - name: Wait for /var/lib/dpkg/lock-frontend to be released 
    shell: while lsof /var/lib/dpkg/lock-frontend ; do sleep 10; done;
  
  - name: install nginx
    apt: 
      name: nginx
      update_cache: yes 
    register: apt_res
    retries: 5
    until: apt_res is success

  - name: Create Nginx Config for ALB
    template:
      src: templates/alb.j2
      dest: "/etc/nginx/sites-available/alb"
      owner: root
      group: root
      mode: '0644'

  - name: Link to enable configuration
    file: >
          dest=/etc/nginx/sites-enabled/default
          src=/etc/nginx/sites-available/alb
          state=link

  - name: Restart Nginx
    service: 
      name: nginx 
      state: restarted
